### ISSUE TITLE
Complete Repository on GitHub

### ISSUE THREAD

**Issue by Christoph21x** [carlospuk/remotepotato#3]
- Silverlight / UI sources
- iPhone Client (?)
- Android Client (Remote Media Center) (?)

**Comment by carlospuk** [comment]
Hi Christoph

The Silverlight UI source will appear hear soon; at the moment it is not buildable, so instead the built .xap is included - sorry about this, the various projects are scattered across hard drives etc so I'm trying to create a buildable project before I upload it.  Added complication that the SilverLiveStreamingSource library isn't open source.

The clients you mention are not open source software.

Carl

**Comment by Christoph21x** [comment]
Hi Carl,
didn't want to offend, I read the explanation in the previously closed thread.
I just wanted to point out, that this issue is open - and still is. So I would ask you to re-open it. I will delete the two apps out of it, but the rest is open. We're on a development platform, right?

Chris
