### ISSUE TITLE
Wrong Aspect Ratio

### ISSUE THREAD

**Issue by joshpollard** [carlospuk/remotepotato#8]
No matter what I send in my request custom parameters the video always come back with what looks like a 4:3 aspect ratio. Does anyone know what I'm doing wrong, or have any suggestions?

**Comment by piet5211** [comment]
try to send < OutputSquarePixels > false < /OutputSquarePixels > along with your custom parameters.

**Comment by joshpollard** [comment]
I thought for sure I had tried that. I tried it again, and it's working now. Thanks!
